version: '3.3'

services:
  backend:
    image: node:12-alpine
    ports: 
      - "8080:3000"
    restart: always
    environment:
      DB_KEY: xxx # TODO: fix later
      DB_ENDPOINT: xxx # TODO: fix later

  frontend: 
    image: node:12-alpine
    restart: always
    environment:
      BACKEND_PORT: 5000 #TODO: fix later
    depends_on: 
      - backend
    